[package]
name = "protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
tonic-build.workspace = true
tonic.workspace = true
prost.workspace = true
dashmap.workspace = true
tokio-util.workspace = true